'use client'

import { useEffect, useMemo, useState } from 'react'
import {
  Activity, ArrowUpRight, Bell, Bot, BrainCircuit, Check, CheckCircle2, ChevronRight,
  CircleHelp, Clock3, FileText, Gauge, LayoutDashboard, Menu, Plus, Search, Send,
  Settings2, ShieldCheck, Sparkles, Target, Users, X, Zap, BookOpen, BarChart3,
  Workflow, AlertTriangle, RotateCcw, Database, ExternalLink
} from 'lucide-react'
import { Approval, DemoStateManager, KnowledgeSource, Specialist, TaskRun } from '@/lib/demo-state'

type View = 'Overview' | 'Lesedi' | 'Workflows' | 'Approvals' | 'Opportunities' | 'Knowledge' | 'Impact'

const nav: { label: View; icon: typeof LayoutDashboard }[] = [
  { label: 'Overview', icon: LayoutDashboard }, { label: 'Lesedi', icon: Bot },
  { label: 'Workflows', icon: Zap }, { label: 'Approvals', icon: ShieldCheck },
  { label: 'Opportunities', icon: Target }, { label: 'Knowledge', icon: BookOpen }, { label: 'Impact', icon: BarChart3 },
]

export default function Page() {
  const [open, setOpen] = useState(false)
  const [active, setActive] = useState<View>('Overview')
  const [prompt, setPrompt] = useState('')
  const [thinking, setThinking] = useState(false)
  const [manager, setManager] = useState<DemoStateManager | null>(null)
  const [tasks, setTasks] = useState<TaskRun[]>([])
  const [approvals, setApprovals] = useState<Approval[]>([])
  const [audits, setAudits] = useState<any[]>([])

  useEffect(() => {
    const next = new DemoStateManager()
    setManager(next); setTasks(next.getTasks()); setApprovals(next.getApprovals()); setAudits(next.getAudits())
  }, [])

  const pendingApprovals = approvals.filter(a => a.status === 'pending')
  const refresh = () => { if (!manager) return; setTasks([...manager.getTasks()]); setApprovals([...manager.getApprovals()]); setAudits([...manager.getAudits()]) }
  async function submitTask(value = prompt) {
    if (!manager || !value.trim() || thinking) return
    setThinking(true)
    await new Promise(resolve => setTimeout(resolve, 650))
    await manager.submitTask(value.trim()); setPrompt(''); refresh(); setThinking(false); setActive('Lesedi')
  }
  function review(id: string, approved: boolean) { if (!manager) return; approved ? manager.approveAction(id) : manager.rejectAction(id, 'Not aligned with current priorities'); refresh() }
  function selectView(view: View) { setActive(view); setOpen(false) }

  return <div className="min-h-screen bg-[#080b10] text-white"><div className="flex min-h-screen">
    <aside className={`fixed inset-y-0 left-0 z-30 w-[248px] border-r border-white/[.07] bg-[#0b0f15] p-4 transition-transform lg:static lg:translate-x-0 ${open ? 'translate-x-0' : '-translate-x-full'}`}>
      <div className="mb-8 flex items-center justify-between px-2"><div className="flex items-center gap-2.5"><img src="https://hebbkx1anhila5yf.public.blob.vercel-storage.com/file_00000000def48211bfd84a5c87b08de3-BxT08UsSGR999A2E7LcJ6f786BakVh.png" alt="Lesedi AnI logo" className="size-9 rounded-lg object-cover" /><div><div className="text-[15px] font-semibold tracking-wide text-amber-100">Lesedi AnI</div><div className="text-[10px] uppercase tracking-[.18em] text-amber-200/50">She who brings light</div></div></div><button aria-label="Close menu" className="lg:hidden" onClick={() => setOpen(false)}><X className="size-4" /></button></div>
      <div className="mb-6 rounded-xl border border-white/[.07] bg-white/[.025] p-3"><div className="mb-2 text-[10px] uppercase tracking-[.16em] text-slate-500">Workspace</div><div className="flex items-center gap-2.5"><div className="grid size-7 place-items-center rounded-lg bg-emerald-500/15 text-[11px] font-bold text-emerald-300">U</div><div className="text-sm font-medium">Ubuntu Threads</div></div></div>
      <div className="mb-2 px-3 text-[10px] font-semibold uppercase tracking-[.16em] text-slate-600">Command center</div><nav className="flex flex-col gap-1">{nav.map(({ label, icon: Icon }) => <button key={label} onClick={() => selectView(label)} className={`flex w-full items-center gap-3 rounded-lg px-3 py-2.5 text-left text-[13px] ${active === label ? 'bg-amber-500/12 text-amber-200' : 'text-slate-400 hover:bg-white/[.04]'}`}><Icon className="size-4" /><span>{label}</span>{label === 'Approvals' && pendingApprovals.length > 0 && <span className="ml-auto rounded-full bg-amber-400/15 px-1.5 py-0.5 text-[10px] text-amber-300">{pendingApprovals.length}</span>}</button>)}</nav>
      <div className="absolute bottom-4 left-4 right-4 border-t border-white/[.07] pt-4"><button className="mb-2 flex items-center gap-3 px-3 py-2 text-[13px] text-slate-400"><Settings2 className="size-4" />Settings</button><button className="flex items-center gap-3 px-3 py-2 text-[13px] text-slate-400"><CircleHelp className="size-4" />Help center</button></div>
    </aside>{open && <button className="fixed inset-0 z-20 bg-black/60 lg:hidden" onClick={() => setOpen(false)} aria-label="Close navigation" />}
    <main className="min-w-0 flex-1"><header className="flex h-[68px] items-center justify-between border-b border-white/[.07] px-5 sm:px-8"><button aria-label="Open menu" onClick={() => setOpen(true)} className="lg:hidden"><Menu className="size-5" /></button><div className="hidden items-center gap-2 text-sm text-slate-500 sm:flex"><LayoutDashboard className="size-4" />Workspace <span>/</span><span className="text-slate-300">{active}</span></div><div className="flex items-center gap-3"><div className="hidden items-center gap-2 rounded-lg border border-white/[.08] bg-white/[.025] px-3 py-2 text-xs text-slate-500 sm:flex"><Search className="size-3.5" />Search <kbd>⌘ K</kbd></div><Bell className="size-4 text-slate-400" /><span className="hidden items-center gap-1.5 text-[10px] text-emerald-300 sm:flex"><span className="size-1.5 rounded-full bg-emerald-400" />Demo runtime</span></div></header>
      <div className="mx-auto max-w-[1240px] px-5 py-8 sm:px-8 lg:px-10">{active === 'Overview' && <Overview onNavigate={selectView} onPrompt={submitTask} pending={pendingApprovals.length} tasks={tasks} audits={audits} />}{active === 'Lesedi' && <Lesedi prompt={prompt} setPrompt={setPrompt} submitTask={submitTask} thinking={thinking} tasks={tasks} />}{active === 'Approvals' && <Approvals approvals={approvals} review={review} />}{active === 'Knowledge' && <Knowledge />}{active === 'Impact' && <Impact tasks={tasks} audits={audits} />}{active === 'Workflows' && <SimpleView title="Workflows" icon={Workflow} description="Reusable operating rhythms are ready to be connected to your team." items={['Weekly pipeline review', 'Content approval loop', 'Market signal digest']} />}{active === 'Opportunities' && <SimpleView title="Opportunities" icon={Target} description="Potential moves identified from your workspace context." items={['Expand Ubuntu Threads into education', 'Package the intelligence audit', 'Partner with local creator networks']} />}</div></main>
  </div></div>
}

function Overview({ onNavigate, onPrompt, pending, tasks, audits }: { onNavigate: (v: View) => void; onPrompt: (v: string) => void; pending: number; tasks: TaskRun[]; audits: any[] }) {
  return <><section className="mb-8"><div className="mb-2 flex items-center gap-2 text-xs font-medium text-amber-300"><span className="size-1.5 rounded-full bg-amber-400" />VAH LABS · ANCESTRAL INTELLIGENCE</div><h1 className="text-3xl font-semibold tracking-[-.035em] sm:text-[34px]">Good morning. Lesedi is ready.</h1><p className="mt-2 text-sm text-slate-400">Your intelligence team can research, plan and prepare work while you remain in control.</p></section>
  <section className="mb-7 grid grid-cols-2 gap-3 lg:grid-cols-4"><Kpi icon={Gauge} label="Runtime" value="Ready" sub="Local demo" /><Kpi icon={ShieldCheck} label="Approvals" value={pending ? `${pending} pending` : 'Clear'} sub="Human controlled" /><Kpi icon={Target} label="Knowledge" value="4 sources" sub="Workspace context" /><Kpi icon={Activity} label="Audit" value={`${audits.length} events`} sub="Every run recorded" /></section>
  <section className="mb-7 overflow-hidden rounded-2xl border border-amber-400/20 bg-gradient-to-br from-[#15152d] via-[#101421] to-[#0d111a]"><div className="grid gap-8 p-6 lg:grid-cols-[1.05fr_.95fr] lg:p-10"><div className="flex flex-col justify-center"><div className="mb-4 flex items-center gap-2 text-xs font-medium text-amber-300"><BrainCircuit className="size-4" />LESEDI · CHIEF OF STAFF</div><h2 className="max-w-xl text-2xl font-semibold leading-tight sm:text-3xl">Turn your next idea into your next advantage.</h2><p className="mt-3 max-w-lg text-sm leading-6 text-slate-400">Lesedi understands the request, routes it to the right intelligence specialist, uses your saved business context, and asks for approval before sensitive actions.</p><div className="mt-6 flex flex-wrap gap-2">{['Find new opportunities','Review my pipeline','Plan my week'].map(x => <button key={x} onClick={() => onPrompt(x)} className="rounded-full border border-white/10 bg-white/[.03] px-3 py-2 text-xs text-slate-300 hover:bg-white/[.07]">{x}</button>)}</div></div><div className="rounded-2xl border border-white/10 bg-[#0a0e17]/90 p-4 shadow-xl"><div className="mb-3 flex items-center justify-between"><div className="flex items-center gap-2 text-xs font-medium text-slate-300"><Bot className="size-4 text-amber-300" />Ask Lesedi</div><span className="rounded-full border border-emerald-400/20 bg-emerald-400/10 px-2 py-1 text-[10px] text-emerald-300">Local demo</span></div><textarea aria-label="Ask Lesedi" onKeyDown={e => { if (e.key === 'Enter' && !e.shiftKey && !e.nativeEvent.isComposing && e.keyCode !== 229) { e.preventDefault(); onPrompt((e.target as HTMLTextAreaElement).value) } }} placeholder="What would you like Lesedi to move forward?" className="min-h-[120px] w-full resize-none rounded-xl border border-white/[.08] bg-white/[.025] p-3 text-sm leading-6 outline-none placeholder:text-slate-600 focus:border-amber-400/50" /><div className="mt-3 flex items-center justify-between"><span className="text-[10px] text-slate-600">Enter to send · Shift + Enter for a new line</span><button onClick={() => onNavigate('Lesedi')} className="flex items-center gap-2 rounded-lg bg-amber-500 px-3 py-2 text-xs font-medium text-white hover:bg-amber-400">Open Lesedi <ArrowUpRight className="size-3.5" /></button></div></div></div></section>
  <div className="mb-7 grid gap-5 lg:grid-cols-[1.15fr_.85fr]"><section className="rounded-2xl border border-white/[.08] bg-[#0d121a] p-5 sm:p-6"><Header title="Your intelligence team" action="View team" /><div className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-4">{new DemoStateManager().getSpecialists().map(s => <div key={s.id} className="rounded-xl border border-white/[.07] bg-white/[.02] p-3"><div className="mb-3 grid size-9 place-items-center rounded-xl bg-amber-500/15 text-[10px] font-bold text-amber-200">{s.initials}</div><div className="text-xs font-medium">{s.name}</div><div className="mt-1 text-[10px] text-slate-500">{s.role}</div><div className="mt-3 text-[10px] text-emerald-400">● Available</div></div>)}</div></section><section className="rounded-2xl border border-white/[.08] bg-[#0d121a] p-5 sm:p-6"><Header title="Recent activity" action="View audit" />{tasks.length ? <div className="mt-5 flex flex-col gap-3">{tasks.slice(-3).reverse().map(t => <div key={t.id} className="flex gap-3"><div className="mt-1 grid size-6 shrink-0 place-items-center rounded-full bg-amber-500/15"><CheckCircle2 className="size-3.5 text-amber-300" /></div><div><div className="text-xs text-slate-300">{t.specialist.name} completed a run</div><div className="mt-1 text-[10px] text-slate-500">{t.input}</div></div></div>)}</div> : <div className="mt-5 text-xs text-slate-500">Your first Lesedi run will appear here.</div>}</section></div>
  <section className="grid gap-5 lg:grid-cols-3"><ActionCard icon={ShieldCheck} title="Approvals" text="Sensitive actions pause for human review." onClick={() => onNavigate('Approvals')} /><ActionCard icon={FileText} title="Knowledge" text="Workspace sources are available to the Chief." onClick={() => onNavigate('Knowledge')} /><ActionCard icon={Users} title="Impact" text="Every run can be audited and measured." onClick={() => onNavigate('Impact')} /></section></>
}

function Lesedi({ prompt, setPrompt, submitTask, thinking, tasks }: { prompt: string; setPrompt: (v: string) => void; submitTask: (v?: string) => void; thinking: boolean; tasks: TaskRun[] }) {
  return <><PageHeading eyebrow="CHIEF OF STAFF" title="Ask Lesedi" description="Delegate research, planning and preparation to your intelligence team." icon={Bot} /><div className="grid gap-5 lg:grid-cols-[.9fr_1.1fr]"><section className="rounded-2xl border border-amber-400/20 bg-[#101421] p-5"><div className="mb-3 flex items-center gap-2 text-xs text-amber-300"><Bot className="size-4" />Lesedi workspace</div><textarea value={prompt} onChange={e => setPrompt(e.target.value)} onKeyDown={e => { if (e.key === 'Enter' && !e.shiftKey && !e.nativeEvent.isComposing && e.keyCode !== 229) { e.preventDefault(); submitTask() } }} placeholder="What would you like to move forward?" className="min-h-[180px] w-full resize-none rounded-xl border border-white/10 bg-black/20 p-4 text-sm leading-6 outline-none placeholder:text-slate-600 focus:border-amber-400/50" /><div className="mt-3 flex items-center justify-between"><span className="text-[10px] text-slate-500">Requests that send, publish, change or execute create an approval.</span><button disabled={thinking} onClick={() => submitTask()} className="flex items-center gap-2 rounded-lg bg-amber-500 px-4 py-2 text-xs font-medium disabled:opacity-50">{thinking ? 'Thinking...' : 'Send'}<Send className="size-3.5" /></button></div></section><section className="rounded-2xl border border-white/[.08] bg-[#0d121a] p-5"><div className="mb-5 flex items-center justify-between"><h2 className="text-sm font-medium">Run history</h2><span className="text-[10px] text-slate-500">{tasks.length} total</span></div>{tasks.length ? <div className="flex flex-col gap-4">{tasks.slice().reverse().map(task => <div key={task.id} className="rounded-xl border border-white/[.07] bg-white/[.02] p-4"><div className="flex items-start justify-between gap-4"><div><div className="text-xs font-medium text-amber-200">{task.specialist.name}</div><div className="mt-1 text-sm text-slate-300">{task.input}</div></div><Status status={task.status} /></div><p className="mt-3 text-xs leading-5 text-slate-500">{task.response}</p>{task.requiresApproval && <div className="mt-3 flex items-center gap-2 text-[10px] text-amber-300"><AlertTriangle className="size-3.5" />Waiting for human approval</div>}</div>)}</div> : <EmptyState icon={Bot} text="No runs yet. Ask Lesedi to start." />}</section></div></>
}

function Approvals({ approvals, review }: { approvals: Approval[]; review: (id: string, approved: boolean) => void }) { return <><PageHeading eyebrow="CONTROL PLANE" title="Approvals" description="Keep sensitive actions paused until a human makes the call." icon={ShieldCheck} />{approvals.length ? <div className="flex flex-col gap-3">{approvals.slice().reverse().map(a => <div key={a.id} className="rounded-2xl border border-white/[.08] bg-[#0d121a] p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="mb-2 flex items-center gap-2"><Status status={a.status} /><span className="text-[10px] text-slate-500">{a.specialist}</span></div><h2 className="text-sm font-medium text-slate-200">{a.action}</h2><p className="mt-2 max-w-2xl text-xs leading-5 text-slate-500">{a.proposed}</p></div>{a.status === 'pending' && <div className="flex gap-2"><button onClick={() => review(a.id, false)} className="rounded-lg border border-white/10 px-3 py-2 text-xs text-slate-300">Reject</button><button onClick={() => review(a.id, true)} className="flex items-center gap-2 rounded-lg bg-emerald-500/15 px-3 py-2 text-xs text-emerald-300"><Check className="size-3.5" />Approve</button></div>}</div></div>)}</div> : <EmptyState icon={CheckCircle2} text="No approval requests. You are in control." />}</> }

function Knowledge() { const sources = new DemoStateManager().getKnowledge(); return <><PageHeading eyebrow="BUSINESS BRAIN" title="Knowledge" description="The local demo workspace context available to Lesedi." icon={BookOpen} /><div className="mb-5 flex items-center justify-between rounded-xl border border-amber-400/15 bg-amber-400/[.04] p-4 text-xs text-amber-200"><div className="flex items-center gap-3"><Database className="size-4" /><span>This MVP uses seeded local knowledge. Connect a database later for live workspace sources.</span></div><span className="rounded-full border border-amber-300/20 px-2 py-1 text-[10px]">Demo</span></div><div className="grid gap-3 md:grid-cols-2">{sources.map((source: KnowledgeSource) => <div key={source.id} className="rounded-2xl border border-white/[.08] bg-[#0d121a] p-5"><div className="mb-4 flex items-start justify-between"><div className="grid size-9 place-items-center rounded-xl bg-amber-500/15"><FileText className="size-4 text-amber-300" /></div><span className="rounded-full bg-white/[.05] px-2 py-1 text-[10px] text-slate-400">{source.category}</span></div><h2 className="text-sm font-medium">{source.name}</h2><p className="mt-2 text-xs leading-5 text-slate-500">{source.snippet}</p><div className="mt-4 flex items-center gap-1 text-[10px] text-emerald-300"><CheckCircle2 className="size-3" />Available to Lesedi</div></div>)}</div></> }

function Impact({ tasks, audits }: { tasks: TaskRun[]; audits: any[] }) { return <><PageHeading eyebrow="MEASUREMENT" title="Impact" description="A clear view of what your intelligence team is moving forward." icon={BarChart3} /><div className="grid gap-3 md:grid-cols-3"><Kpi icon={Zap} label="Runs completed" value={`${tasks.filter(t => t.status === 'completed').length}`} sub="Across all specialists" /><Kpi icon={Clock3} label="Awaiting review" value={`${tasks.filter(t => t.status === 'awaiting_approval').length}`} sub="Human decisions" /><Kpi icon={Activity} label="Audit events" value={`${audits.length}`} sub="Local activity log" /></div><div className="mt-5 rounded-2xl border border-white/[.08] bg-[#0d121a] p-5"><h2 className="mb-4 text-sm font-medium">Activity audit</h2>{audits.length ? <div className="flex flex-col gap-3">{audits.slice().reverse().map((audit: any) => <div key={audit.id} className="flex items-start gap-3 border-b border-white/[.06] pb-3 last:border-0"><Activity className="mt-0.5 size-3.5 text-amber-300" /><div><div className="text-xs text-slate-300">{audit.action}</div><div className="mt-1 text-[10px] text-slate-500">{audit.details}</div></div></div>)}</div> : <EmptyState icon={Activity} text="Audit events appear after your first run." />}</div></> }

function SimpleView({ title, icon: Icon, description, items }: { title: string; icon: typeof Target; description: string; items: string[] }) { return <><PageHeading eyebrow="COMMAND CENTER" title={title} description={description} icon={Icon} /><div className="grid gap-3 md:grid-cols-3">{items.map((item, index) => <div key={item} className="rounded-2xl border border-white/[.08] bg-[#0d121a] p-5"><div className="mb-5 flex size-9 items-center justify-center rounded-xl bg-amber-500/15 text-xs text-amber-200">0{index + 1}</div><h2 className="text-sm font-medium">{item}</h2><p className="mt-2 text-xs leading-5 text-slate-500">Ready for your workspace context and team ownership.</p><button className="mt-5 flex items-center gap-1 text-[10px] text-amber-300">Open workflow <ChevronRight className="size-3" /></button></div>)}</div></> }

function PageHeading({ eyebrow, title, description, icon: Icon }: { eyebrow: string; title: string; description: string; icon: typeof Bot }) { return <section className="mb-8"><div className="mb-2 flex items-center gap-2 text-xs font-medium text-amber-300"><Icon className="size-3.5" />{eyebrow}</div><h1 className="text-3xl font-semibold tracking-[-.035em]">{title}</h1><p className="mt-2 text-sm text-slate-400">{description}</p></section> }
function Kpi({ icon: Icon, label, value, sub }: { icon: typeof Gauge; label: string; value: string; sub: string }) { return <div className="rounded-xl border border-white/[.08] bg-[#0d121a] p-4"><Icon className="mb-3 size-4 text-amber-300" /><div className="text-sm font-semibold">{value}</div><div className="mt-1 text-[11px] text-slate-400">{label}</div><div className="mt-1 text-[10px] text-slate-600">{sub}</div></div> }
function Header({ title, action }: { title: string; action: string }) { return <div className="flex items-center justify-between"><h3 className="text-sm font-medium">{title}</h3><button className="flex items-center gap-1 text-[10px] text-slate-500">{action}<ChevronRight className="size-3" /></button></div> }
function ActionCard({ icon: Icon, title, text, onClick }: { icon: typeof ShieldCheck; title: string; text: string; onClick: () => void }) { return <button onClick={onClick} className="rounded-2xl border border-white/[.08] bg-[#0d121a] p-5 text-left hover:border-amber-400/30"><Icon className="mb-4 size-4 text-amber-300" /><div className="text-sm font-medium">{title}</div><p className="mt-2 text-xs leading-5 text-slate-500">{text}</p><ArrowUpRight className="mt-4 size-4 text-slate-600" /></button> }
function EmptyState({ icon: Icon, text }: { icon: typeof Bot; text: string }) { return <div className="flex min-h-40 flex-col items-center justify-center gap-3 rounded-xl border border-dashed border-white/[.08] text-center"><Icon className="size-5 text-slate-600" /><p className="text-xs text-slate-500">{text}</p></div> }
function Status({ status }: { status: string }) { const config: Record<string, { label: string; className: string }> = { pending: { label: 'Pending', className: 'text-amber-300 bg-amber-400/10 border-amber-400/20' }, approved: { label: 'Approved', className: 'text-emerald-300 bg-emerald-400/10 border-emerald-400/20' }, rejected: { label: 'Rejected', className: 'text-red-300 bg-red-400/10 border-red-400/20' }, awaiting_approval: { label: 'Awaiting approval', className: 'text-amber-300 bg-amber-400/10 border-amber-400/20' }, completed: { label: 'Completed', className: 'text-emerald-300 bg-emerald-400/10 border-emerald-400/20' } }; const item = config[status] || config.pending; return <span className={`rounded-full border px-2 py-1 text-[10px] ${item.className}`}>{item.label}</span> }

void Plus; void RotateCcw; void ExternalLink
